version: '3.9'

services:
  admin:
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: xxl_job_admin
    restart: always
    hostname: admin
    ports:
      - "7070:8080"
    volumes:
      - ./data/logs:/data/applogs
      - ./data/xxl-job/:/xxl-job
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://<服务器IP地址>:3306/xxl_job?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
